# Generated by Django 2.2.4 on 2019-09-15 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso_Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Acceso del modulo',
            },
        ),
        migrations.CreateModel(
            name='Cantidad_semanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.IntegerField()),
                ('martes', models.IntegerField()),
                ('miercoles', models.IntegerField()),
                ('jueves', models.IntegerField()),
                ('viernes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Convocatoria',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.TimeField(null=True)),
                ('fecha_fin', models.TimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='Tipo_beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('REFRIGERIO', 'REFRIGERIO'), ('ALMUERZO', 'ALMUERZO')], max_length=50)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('cantidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Cantidad_semanal', verbose_name='Cantidad')),
            ],
            options={
                'verbose_name_plural': 'Tipo de beneficio',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='perfil/')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Horario', verbose_name='Horario')),
                ('tipo_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Tipo_beneficio', verbose_name='Tipo beneficio')),
            ],
            options={
                'verbose_name_plural': 'Modulo',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(null=True, upload_to='perfil/')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Convocatoria', verbose_name='Convocatoria')),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Estudiante', verbose_name='Convocatoria')),
                ('tipo_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Tipo_beneficio', verbose_name='Tipo beneficio')),
            ],
            options={
                'verbose_name_plural': 'Beneficiario',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('acceso_modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Acceso_Modulo', verbose_name='Acceso Modulo')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Beneficiario', verbose_name='Beneficiario')),
            ],
            options={
                'verbose_name_plural': 'Asistencia',
            },
        ),
        migrations.AddField(
            model_name='acceso_modulo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Modulo', verbose_name='Modulo'),
        ),
        migrations.AddField(
            model_name='acceso_modulo',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Personal', verbose_name='Personal'),
        ),
    ]
