# Generated by Django 2.2.4 on 2019-10-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField()),
                ('martes', models.BooleanField()),
                ('miercoles', models.BooleanField()),
                ('jueves', models.BooleanField()),
                ('viernes', models.BooleanField()),
                ('tipo_beneficio', models.CharField(choices=[('REFRIGERIO', 'REFRIGERIO'), ('ALMUERZO', 'ALMUERZO')], max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='deportista',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estrato',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='jovenes_accion',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pension_de',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pension_ud',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Preseleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('SELECCION', 'SELECCION'), ('PRESELECCION', 'PRESELECCION')], max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Estudiante', verbose_name='Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Registro_estudiante', verbose_name='Registro Estudiante'),
        ),
    ]
