# Generated by Django 2.2.4 on 2019-09-06 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso_Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.CharField(max_length=300, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Horario', verbose_name='Horario')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='perfil/')),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
        migrations.AddField(
            model_name='modulo',
            name='tipo_beneficio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Tipo_beneficio', verbose_name='Tipo beneficio'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='convocatoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Convocatoria', verbose_name='Convocatoria'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='tipo_beneficio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Tipo_beneficio', verbose_name='Tipo beneficio'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Beneficiario', verbose_name='Beneficiario'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Modulo', verbose_name='Modulo'),
        ),
        migrations.AddField(
            model_name='acceso_modulo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Modulo', verbose_name='Modulo'),
        ),
        migrations.AddField(
            model_name='acceso_modulo',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega.Personal', verbose_name='Personal'),
        ),
    ]
