# Generated by Django 2.2.4 on 2019-10-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0002_auto_20191026_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='registro',
        ),
        migrations.AddField(
            model_name='registro_estudiante',
            name='estado',
            field=models.CharField(choices=[('SELECCION', 'SELECCION'), ('PRESELECCION', 'PRESELECCION')], default='PRESELECCION', max_length=100),
        ),
        migrations.AddField(
            model_name='registro_estudiante',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='registro_estudiante',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registro_estudiante',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registro_estudiante',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registro_estudiante',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registro_estudiante',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Preseleccion',
        ),
    ]
