# Generated by Django 2.2.4 on 2019-10-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0003_auto_20191027_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
    ]
