# Generated by Django 2.2.4 on 2019-09-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0004_auto_20190906_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Estudiante', verbose_name='Convocatoria'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='tipo_beneficio',
            name='nombre',
            field=models.CharField(choices=[('REFRIGERIO', 'REFRIGERIO'), ('ALMUERZO', 'ALMUERZO')], max_length=50),
        ),
    ]
