# Generated by Django 2.2.4 on 2019-11-24 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0004_auto_20191027_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('sanciones', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Estudiante', verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('suministro', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CARNES', 'CARNES'), ('BEBIDAS', 'BEBIDAS'), ('LACTAEO', 'LACTEOS'), ('FRUTAS Y VERDURAS', 'FRUTAS Y VERDURAS'), ('GRANOS', 'GRANOS'), ('OTROS', 'OTROS')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('encargado_sede', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Proveedor', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_falla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('falla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Falla', verbose_name='Falla')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Sede', verbose_name='sede'),
        ),
        migrations.AddField(
            model_name='registro_estudiante',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Sede', verbose_name='sede'),
        ),
    ]
