# Generated by Django 2.2.4 on 2019-11-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0005_auto_20191124_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='falla',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro_pedido',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'SOLICITADO'), ('EN PROCESO', 'EN PROCESO'), ('ENTREGADO', 'ENTEGRADO'), ('RECHAZADO', 'RECHAZADO')], max_length=100),
        ),
    ]
