# Generated by Django 2.2.4 on 2019-09-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0006_auto_20190914_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='fecha_final',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fecha_inicio',
            field=models.TimeField(null=True),
        ),
    ]
