# Generated by Django 2.2.4 on 2019-09-15 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0007_auto_20190914_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='fecha_final',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fecha_inicio',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
    ]
