# Generated by Django 2.2.4 on 2019-09-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0008_auto_20190914_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='modulo',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='acceso_modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrega.Acceso_Modulo', verbose_name='Acceso Modulo'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fecha_final',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fecha_inicio',
            field=models.TimeField(),
        ),
    ]
