# Generated by Django 2.2.4 on 2019-09-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0010_auto_20190915_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='horario',
            name='fecha_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='fecha_ini',
            field=models.TimeField(null=True),
        ),
    ]
